spring.application.name=chinook-api

#Database
spring.datasource.url=${DB_URL:jdbc:sqlserver://localhost:1433;databaseName=Chinook;trustServerCertificate=true}
spring.datasource.username=${DB_USERNAME:sa}
spring.datasource.password=${DB_PASSWORD:}
spring.datasource.driver-class-name=${DB_DRIVER:com.microsoft.sqlserver.jdbc.SQLServerDriver}

# JDBC logging
logging.level.org.springframework.jdbc.core=DEBUG
logging.level.org.hibernate.SQL=DEBUG
logging.level.org.hibernate.orm.jdbc.bind=TRACE


